server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h

storage:
  trace:
    backend: local
    local: # configuration block for local storage
      path: /tmp/tempo/blocks
    wal:   # configuration block for the Write Ahead Log (WAL)
      path: /tmp/tempo/wal