# Server configuration
server:
  port: ${ADMIN_SERVICE_PORT:9080}

# Spring Boot Admin Configuration
spring:
  boot:
    admin:
      server:
        enabled: true
      context-path: /
      monitor:
        default-retries: 2
        status-interval: 10000
        status-lifetime: 10000
      probed-endpoints: info
      ui:
        title: Healthcare Admin Panel

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
        liveness:
          include: "*"
  ## OpenTelemetry Metrics config
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  ## OpenTelemetry Tracing config
  tracing:
    enabled: true
    sampling:
      # Management tracing sampling probability (1.0 = 100% traces sampled) for dev environment only
      probability: 1.0
  otlp:
    # OTLP Metrics Exporter config
    metrics:
      export:
        enabled: ${OTLP_METRICS_EXPORT_ENABLED:true}
        url: ${OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
    # OTLP Tracing Exporter config
    tracing:
      export:
        enabled: ${OTLP_TRACING_EXPORT_ENABLED:true}
      transport: ${OTLP_TRACING_EXPORT_TRANSPORT-TYPE:http}
      endpoint: ${OTLP_TRACING_EXPORT_URL:http://localhost:4318/v1/traces}
    # OTLP Logging Exporter config
    logging:
      export:
        enabled: ${OTLP_LOGGING_EXPORT_ENABLED:true}
      transport: ${OTLP_LOGGING_EXPORT_TRANSPORT-TYPE:http}
      endpoint: ${OTLP_LOGGING_EXPORT_URL:http://localhost:4318/v1/logs}
