spring:
  cloud:
    config:
      enabled: false
  boot:
    admin:
      client:
        enabled: false
        instance:
          name: Doctor Service
          service-url: ${ADMIN_CLIENT_INSTANCE_SERVICE_URL:http://127.0.0.1:8080}
        url: ${ADMIN_CLIENT_URL:http://127.0.0.1:9080}
        auto-registration: true
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:rootpassword@127.0.0.1:27017/healthcare?authSource=admin}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.servlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
        liveness:
          include: "*"
  ## OpenTelemetry Metrics config
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  ## OpenTelemetry Tracing config
  tracing:
    enabled: true
    sampling:
      # Management tracing sampling probability (1.0 = 100% traces sampled) for dev environment only
      probability: 1.0
  otlp:
    # OTLP Metrics Exporter config
    metrics:
      export:
        enabled: ${OTLP_METRICS_EXPORT_ENABLED:true}
        url: ${OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
    # OTLP Tracing Exporter config
    tracing:
      export:
        enabled: ${OTLP_TRACING_EXPORT_ENABLED:true}
      transport: ${OTLP_TRACING_EXPORT_TRANSPORT-TYPE:http}
      endpoint: ${OTLP_TRACING_EXPORT_URL:http://localhost:4318/v1/traces}
    # OTLP Logging Exporter config
    logging:
      export:
        enabled: ${OTLP_LOGGING_EXPORT_ENABLED:true}
      transport: ${OTLP_LOGGING_EXPORT_TRANSPORT-TYPE:http}
      endpoint: ${OTLP_LOGGING_EXPORT_URL:http://localhost:4318/v1/logs}

server:
  port: ${DOCTOR_SERVICE_PORT:8280}
